'use client'
import { Toaster } from "@/components/ui/toaster";
// import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { NotificationProvider } from "@/contexts/NotificationContext";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
        <NotificationProvider>
            {children}
            <Toaster />
          </NotificationProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
